In [1]:
import numpy as np #python society에서 암묵적 합의로 된 alias np

# 넘파이 배열 (ndarray)
● list라는 단어 X eg. 넘파이 list X 넘파이 배열

## list 이용하여 numpy 배열

In [2]:
data1 = [0,1,2,3,4,5]
print(type(data1))

<class 'list'>


In [3]:
print(data1)

[0, 1, 2, 3, 4, 5]


In [4]:
a1 = np.array(data1)
print(type(a1))
print(a1) #파이썬 list와의 차이점

<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [5]:
data2 = [0,1,2,3,4,0.5]

In [6]:
a2 = np.array(data2)
print(a2) #마지막 수가 실수니까 실수가 됨. 두개 이상의 타입을 numpy 배열에 넣지 않는다. type을 체크하지 않고 처리하는 게 빠르니까

[0.  1.  2.  3.  4.  0.5]


In [7]:
#numpy 배열의 element가 무슨 타입인지 알기 위해서는 dtype를 이용한다.
print(a1.dtype, a2.dtype)
#numpy는 정수를 32비트 (4바이트), 실수는 64비트 (8바이트)로 표현

int32 float64


In [8]:
#2차원 배열
a3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## arange 이용한 numpy 배열 
●일반 파이썬의 range 와 사용법은 같음

In [9]:
a4 = np.arange(0,10,2)
print(a4)

[0 2 4 6 8]


In [10]:
a5 = np.arange(1,10)
print(a5)

[1 2 3 4 5 6 7 8 9]


In [11]:
a6 = np.arange(5)
print(a6)

[0 1 2 3 4]


In [12]:
a7 = np.arange(12).reshape(4,3) #row 4, col 3으로 shape
print(a7)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
print(a7.shape) #shape 알아보기

(4, 3)


In [14]:
a7 = np.arange(12).reshape(4,-1) #row 4, 알아서 두번째 차원 주기: -1
print(a7)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [15]:
a7 = np.arange(12).reshape(-1,3)
print(a7)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
a7 = a7.reshape(-1) #무조건 1차원으로 flatten
print(a7)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [17]:
a8 = np.arange(11).reshape(4,3) #row 4, col 3으로 shape
print(a8)

ValueError: cannot reshape array of size 11 into shape (4,3)

In [18]:
a9 = np.arange(12).reshape(2,2,3,1)
print(a9)

[[[[ 0]
   [ 1]
   [ 2]]

  [[ 3]
   [ 4]
   [ 5]]]


 [[[ 6]
   [ 7]
   [ 8]]

  [[ 9]
   [10]
   [11]]]]


## linspace를 활용한 간격 나누기

In [19]:
n1 = np.linspace(1,10,10) #주어진 범위를 세번째 인자로 조각냄
print(n1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [20]:
n1 = np.linspace(1,10,8) 
print(n1)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [21]:
n1 = np.linspace(0, np.pi, 20) #주로 주어진 길이에 눈금을 만들 때 사용됨
print(n1)

[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


## numpy에서 제공하는 특수배열

In [22]:
n = np.zeros(10, int) #shape, 어떤 타입으로 0을 넣을 것인지
print(n)

[0 0 0 0 0 0 0 0 0 0]


In [23]:
n = np.zeros((4,3), int) #zeros는 파라미터 2개만 받으니까 #tuple 쓰는 이유는 변경해 줄 대상이 아니라서
print(n)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [24]:
n = np.zeros((4,3)) #type 생략 시 무조건 실수
print(n)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
n = np.ones(10)
print(n)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [26]:
n = np.ones((4,3), int)
print(n)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [27]:
n = np.eye(5) #단위행렬
print(n)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
a1 = np.array(['1.567', '0.123', '5.232', '5', '8'])
num = a1.astype(float) #numpy 배열의 항목을 바꾸는 것은 astype, type을 확인하는 것은 dtype
print(num)

[1.567 0.123 5.232 5.    8.   ]


In [29]:
a1 = np.array(['1.567', '0.123', '5.232', '5', '8'])
num = a1.astype(int)
print(num)

ValueError: invalid literal for int() with base 10: '1.567'

In [30]:
n = np.array([10, 20, 0.345, 5.87, 9.12])
n2 = n.astype(int)
print(n2)

[10 20  0  5  9]


## 난수배열

In [31]:
np.random.rand() #0 에서 1미만의 난수 생성

0.0486703214058708

In [32]:
np.random.rand(2,3) #2 x 3

array([[0.63073005, 0.34082207, 0.67244937],
       [0.97702607, 0.61299365, 0.82976592]])

In [33]:
np.random.rand(2,3,4) #2 x 3 x 4

array([[[0.87793974, 0.85196408, 0.75300168, 0.99663214],
        [0.86300309, 0.61955747, 0.95272842, 0.82379302],
        [0.42654331, 0.55431886, 0.37207152, 0.20067601]],

       [[0.51364505, 0.80209646, 0.20194479, 0.89680788],
        [0.25556295, 0.92819305, 0.4550941 , 0.77340708],
        [0.39128924, 0.42805808, 0.25286127, 0.08791553]]])

In [34]:
np.random.randint(10, size = (3,4)) #1부터 10미만까지 정수 난수 생성, shape

array([[8, 7, 4, 9],
       [9, 9, 5, 4],
       [6, 7, 6, 2]])

In [35]:
np.random.randint(2,10, size = (3,4))

array([[3, 8, 9, 7],
       [9, 8, 8, 7],
       [5, 8, 7, 3]])

In [36]:
np.random.randint(1,37) #로또 36까지

27

In [37]:
a1 = np.array([10, 20, 30, 40])
a2 = np.array([1, 2, 3, 4])
print(a1 + a2) #원소끼리 계산함 (element-wise calculation) -> 고로 shape이 안맞으면 에러가 남
print(a1 - a2)
print(a1 * 2)
print(a1 ** 2)
print(a1 * a2)
print(a1 / a2)
print(a1 / (a2 ** 2))
print(a1 > 20)
#shift + tab 당기기

[11 22 33 44]
[ 9 18 27 36]
[20 40 60 80]
[ 100  400  900 1600]
[ 10  40  90 160]
[10. 10. 10. 10.]
[10.          5.          3.33333333  2.5       ]
[False False  True  True]


In [38]:
# numpy broadcasting
a1 = np.array([10, 20, 30, 40])
a2 = np.array([1, 2, 3]) #정수배 해서 shape을 맞출 수 있다고 생각하면 broadcasting 해서 맞춰줌
print(a1 + a2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [39]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(8).reshape(2,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]


In [40]:
print(a1 + a2) #shape difference makes element-wise calculation impossible

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

In [41]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]


In [42]:
print(a1+a2)

[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [43]:
a1 = np.arange(1, 6)

print(a1.sum())
print(a1.mean())
print(a1.std())
print(a1.var())
print(a1.min())
print(a1.max())
print(a1.cumsum()) #cumulative sum
print(a1.cumprod()) #cumulative product

15
3.0
1.4142135623730951
2.0
1
5
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [44]:
a = np.array([0, 1, 2, 3]).reshape(2, 2)
print(a)
b = np.array([3, 2, 0, 1]).reshape(2, 2)
print(b)

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]


In [45]:
print(a.dot(b)) #행렬곱  [[0*3 + 0 *0 0*2 + 1+1] [[2*3 + 3*0 2*2+3*1 ]]

[[0 1]
 [6 7]]


In [46]:
print(a.T) #행과 열을 바꿈: 전치 행렬

[[0 2]
 [1 3]]


# slicing

In [47]:
a = np.array([0, 10, 20, 30, 40, 50])

In [48]:
print(a[1]) #list와 마찬가지로 인덱싱 가능

10


In [49]:
print(a[[1, 3, 4]]) #여러개 인덱싱 동시 가능

[10 30 40]


In [50]:
#2차원 배열
b = np.arange(10, 100, 10).reshape(3, 3)

In [51]:
print(b)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [52]:
print(b[0][2])

30


In [53]:
print(b[1])

[40 50 60]


In [54]:
print(b[[0,2], [0,1]])

[10 80]


In [55]:
a = np.array([1, 2, 3, 4, 5, 6])

In [56]:
print(a[a>3]) #인덱싱에 조건 가능

[4 5 6]


In [57]:
print(a[(a%2) == 0])

[2 4 6]


In [58]:
#slicing
a = np.array([0, 10, 20, 30, 40, 50])
print(a[1:4])
print(a[:3])
print(a[2:])
a[2:5] = np.array([25, 35, 45])
print(a)

[10 20 30]
[ 0 10 20]
[20 30 40 50]
[ 0 10 25 35 45 50]


In [59]:
#2차원 slicing
a = np.arange(10, 100, 10).reshape(3, 3)
print(a)
print(a[1:3, 1:3])
print(a[:3, 1:])
print(a[1][0:2])
a[0:2, 1:3] = np.array([[25, 35], [55, 65]]) # 2x2  = 2x2
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[50 60]
 [80 90]]
[[20 30]
 [50 60]
 [80 90]]
[40 50]
[[10 25 35]
 [40 55 65]
 [70 80 90]]


In [1]:
print(a[1][1])
print(a[1,1])

NameError: name 'a' is not defined