In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import layers, models
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from numpy import array

In [2]:
text = '해보지 않으면 해낼 수 없다'

In [3]:
result = text_to_word_sequence(text) #공백 기준으로 list로 변환
print("\n원문:\n", text)
print("\n토큰화:\n", result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [4]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',
       ]

token = Tokenizer()
token.fit_on_texts(docs)

In [5]:
print("\n단어 카운트:\n", token.word_counts) #단어별로 몇번 씩 나왔는지 계산


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 1), ('합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [6]:
print("\n문장 카운트: ", token.document_count)


문장 카운트:  3


In [7]:
print("\n각 단어가 몇 개의 문장에 포함되어 있는가:\n", token.word_docs)


각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'각': 1, '나누어': 1, '합니다': 1, '토큰화': 1, '단어를': 1, '먼저': 1, '텍스트의': 2, '단어로': 1, '토큰화해야': 1, '인식됩니다': 1, '딥러닝에서': 2, '토큰화한': 1, '있습니다': 1, '사용할': 1, '결과는': 1, '수': 1})


In [8]:
print("\n각 단어에 매겨진 인덱스 값:\n",  token.word_index) #0은 특수한 목적으로 사용: 여기에 존재하지 않는 단어가 나왔을 때  (많이 출현한 것부터 줄세워서 indexing)


각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화': 7, '합니다': 8, '단어로': 9, '토큰화해야': 10, '인식됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


In [9]:
text="오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"
token = Tokenizer()
token.fit_on_texts([text]) #fit_on_texts: list를 받음
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [10]:
x=token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [11]:
word_size = len(token.word_index) + 1
#앞자리 비워야 0, +1 안하면 6번 자리 없어짐
x = to_categorical(x, num_classes=word_size)
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [12]:
# 텍스트 리뷰 자료를 지정합니다.
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1,1,1,1,1,0,0,0,0,0])

# 토큰화 
token = Tokenizer()
token.fit_on_texts(docs) #단어 index
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [13]:
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  x) #원 문장 숫자 index


리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [14]:
padded_x = pad_sequences(x, 4)  #4보다 짧으면 앞에 0붙여서 padding, 4보다 길면 뒤부터 짤림
print("\n패딩 결과:\n", padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [16]:
# 임베딩에 입력될 단어의 수를 지정합니다.
word_size = len(token.word_index) +1 #20 + 1

# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = models.Sequential()
model.add(layers.Embedding(word_size, 8, input_length=4)) #one-hot encoding의 수천개 단어에 대한 memory 낭비를 해결 -> embedding, 입력 sequence의 길이
#sparse matrix / vector 희소 벡터 -- 1~2 개만 1이고 나머지는 0
#이걸 저차원의 밀집벡터로 변경: word2vec -- 어떤 알고리즘을 쓰느냐에 따라 차이, 해당 단어 주위에 어떤 단어들이 있는지를 감안해서 vector로 바꾼다
#tensorflow에서 word2vec과 같은 개념으로 구현한 class가 Embedding -- 출력 벡터를 8차원 밀집벡터로 만들겠다, 자동으로 1 빼줌 21*8 (입력 받고 8차원만 뱉어줌)
model.add(layers.Flatten()) #4*8
model.add(layers.Dense(1, activation='sigmoid')) #32*1+1
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              168       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 1s 892ms/step - loss: 0.7018 - accuracy: 0.3000
Epoch 2/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6996 - accuracy: 0.3000
Epoch 3/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6974 - accuracy: 0.3000
Epoch 4/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6952 - accuracy: 0.3000
Epoch 5/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6930 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6908 - accuracy: 0.6000
Epoch 7/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6887 - accuracy: 0.6000
Epoch 8/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6865 - accuracy: 0.8000
Epoch 9/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6843 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6822 - accuracy: 0.9000
Epoch 11/20
1/1 [====================